import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { aiRequest } from '../lib/aiApi';
import { resumeRequest, jsonOptions } from '../lib/resumeApi';
import LanguagePicker from '../components/LanguagePicker';
const field = 'w-full border rounded-xl p-3 bg-white';
export default function LearningPathGenerator() {
  const [config, setConfig] = useState({ skill: '', level: 'beginner', weeks: 8, hoursPerWeek: 6, language: 'en-US' });
  const [plan, setPlan] = useState(null); const [history, setHistory] = useState([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function refresh() { const data = await resumeRequest('/api/ai/learning-paths'); setHistory(data.plans); }
  useEffect(() => { let active = true; resumeRequest('/api/ai/learning-paths').then(data => { if (active) setHistory(data.plans); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, []);
  async function perform(action) { if (busy) return; setBusy(true); setError(''); try { await action(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  const tasks = plan?.weeklySchedule.flatMap(week => week.tasks) || []; const completed = new Set(plan?.completedTaskIds || []); const percent = tasks.length ? Math.round(completed.size / tasks.length * 100) : 0;
  return <main className="bg-slate-50 min-h-screen py-10 px-4"><div className="max-w-6xl mx-auto space-y-6"><header><p className="font-semibold text-blue-600">Learn at your level</p><h1 className="text-3xl font-bold mt-2">Your learning roadmap</h1><p className="text-slate-600 mt-2">Choose any skill. Get weekly practice, projects and checkpoints matched to your available time.</p><Link className="text-blue-600 underline" to="/settings">Your profile</Link></header>{error && <p role="alert" className="bg-red-50 text-red-800 p-4 rounded-xl">{error}</p>}<div className="grid lg:grid-cols-[1fr_280px] gap-6"><section className="space-y-5">
  {!plan ? <form className="bg-white border rounded-2xl p-6 space-y-5" onSubmit={e => { e.preventDefault(); perform(async () => { const data = await aiRequest('/learning-path', config); setPlan(data.learningPath); await refresh(); }); }}><label className="block">Skill or goal<input required maxLength={200} className={field} placeholder="Python, public speaking, UI design…" value={config.skill} onChange={e => setConfig({ ...config, skill: e.target.value })} /></label><label className="block">Current level<select className={field} value={config.level} onChange={e => setConfig({ ...config, level: e.target.value })}>{['beginner', 'intermediate', 'advanced'].map(level => <option key={level}>{level}</option>)}</select></label><div className="grid sm:grid-cols-2 gap-4"><label>Weeks<input required type="number" min={2} max={24} className={field} value={config.weeks} onChange={e => setConfig({ ...config, weeks: Number(e.target.value) })} /></label><label>Hours per week<input required type="number" min={2} max={40} className={field} value={config.hoursPerWeek} onChange={e => setConfig({ ...config, hoursPerWeek: Number(e.target.value) })} /></label></div><LanguagePicker label="Guidance language" value={config.language} onChange={language => setConfig({ ...config, language })} /><button disabled={busy} className="rounded-xl bg-blue-600 text-white px-5 py-3 disabled:opacity-40">{busy ? 'Building and saving your roadmap…' : 'Generate roadmap'}</button><p className="text-sm text-slate-500">Your saved roadmap and self-reported progress help your AI Coach recommend the next step.</p></form> : <><div className="bg-white border rounded-2xl p-6 space-y-3"><div className="flex justify-between gap-3"><h2 className="text-2xl font-bold">{plan.skill}</h2><button disabled={busy} className="text-blue-600 underline" onClick={() => setPlan(null)}>New roadmap</button></div><p>{plan.level} · {plan.weeks} weeks · {plan.hoursPerWeek} hours/week</p><p className="whitespace-pre-wrap text-slate-600">{plan.overview}</p><p className="font-medium">{percent}% complete · {completed.size}/{tasks.length} tasks</p><progress value={completed.size} max={tasks.length || 1} className="w-full" /><div className="grid sm:grid-cols-2 gap-4">{['prerequisites', 'outcomes'].map(key => <div key={key}><h3 className="font-semibold capitalize">{key}</h3><ul className="list-disc pl-5">{plan[key].map((value, i) => <li key={i}>{value}</li>)}</ul></div>)}</div></div>
  {plan.weeklySchedule.map(week => <section key={week.week} className="bg-white border rounded-2xl p-6 space-y-4"><h3 className="text-xl font-semibold">Week {week.week}: {week.title}</h3><p className="text-sm text-slate-500">{week.hoursRequired} hours · {week.topics.join(' • ')}</p><p className="bg-blue-50 rounded-xl p-3"><strong>Checkpoint: </strong>{week.milestone}</p>{week.tasks.map(task => <article key={task.id} className="border rounded-xl p-4 space-y-2"><label className="flex items-start gap-3 cursor-pointer"><input type="checkbox" checked={completed.has(task.id)} disabled={busy} onChange={e => { const checked = e.target.checked; perform(async () => { const data = await resumeRequest(`/api/ai/learning-path/${plan._id}/progress`, jsonOptions('PATCH', { taskId: task.id, completed: checked })); setPlan(data.learningPath); await refresh(); }); }} className="mt-1" /><span className="font-semibold">{task.title} <span className="text-sm text-slate-500 font-normal">· {task.estimatedMinutes} min</span></span></label><p className="whitespace-pre-wrap text-slate-600">{task.instructions}</p><p><strong>Deliverable: </strong>{task.deliverable}</p><div className="flex flex-wrap gap-2">{task.resourceQueries.map((query, i) => <a key={i} href={`https://www.google.com/search?q=${encodeURIComponent(query)}`} target="_blank" rel="noopener noreferrer" className="text-sm text-blue-700 underline">Find resources: {query}</a>)}</div></article>)}</section>)}</>}
  </section><aside className="bg-white border rounded-2xl p-5 self-start"><h2 className="font-semibold text-lg">Saved roadmaps</h2><div className="mt-4 space-y-3">{!history.length && <p className="text-sm text-slate-500">Your generated plans appear here.</p>}{history.map(item => <div key={item._id} className="border rounded-xl p-3"><button disabled={busy} className="text-blue-700 font-medium text-left" onClick={() => perform(async () => { const data = await resumeRequest(`/api/ai/learning-path/${item._id}`); setPlan(data.learningPath); })}>{item.skill}</button><p className="text-sm text-slate-500">{item.level} · {item.weeks} weeks</p><button disabled={busy} className="text-red-700 text-sm mt-2" onClick={() => { if (window.confirm('Delete this roadmap and its progress?')) perform(async () => { await resumeRequest(`/api/ai/learning-path/${item._id}`, { method: 'DELETE' }); if (plan?._id === item._id) setPlan(null); await refresh(); }); }}>Delete</button></div>)}</div></aside></div></div></main>;
}
