import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { aiRequest } from '../lib/aiApi';
import { resumeRequest } from '../lib/resumeApi';
import LanguagePicker from '../components/LanguagePicker';
import useInterviewMedia from '../hooks/useInterviewMedia';
const field = 'w-full rounded-xl border border-slate-300 p-3 bg-white';
const button = 'rounded-xl bg-blue-600 px-4 py-3 text-white disabled:opacity-40';
export default function MockInterview() {
  const [config, setConfig] = useState({ topic: '', difficulty: 'beginner', questionCount: 5, language: 'en-US', mode: 'voice' });
  const [session, setSession] = useState(null); const [history, setHistory] = useState([]);
  const [answer, setAnswer] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const media = useInterviewMedia({ language: session?.interviewConfig.language || config.language, onTranscript: text => setAnswer(old => `${old}${old ? ' ' : ''}${text}`.slice(0, 10000)) });
  const index = session?.answers.length || 0; const question = session?.questions[index];
  async function refresh() { try { const data = await resumeRequest('/api/interviews/mine'); setHistory(data.interviews); } catch (e) { setError(e.message); } }
  useEffect(() => { let active = true; resumeRequest('/api/interviews/mine').then(data => { if (active) setHistory(data.interviews); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, []);
  async function perform(action) { if (busy) return; setBusy(true); setError(''); try { await action(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  function stopMedia() { media.stopListening(); media.stopSpeaking(); media.stopCamera(); }
  async function open(id) { await perform(async () => { const data = await resumeRequest(`/api/interviews/${id}`); stopMedia(); setSession(data.interview); setAnswer(''); }); }
  async function start(event) { event.preventDefault(); await perform(async () => { const data = await aiRequest('/interview/start', config); stopMedia(); setSession(data.session); setAnswer(''); await refresh(); }); }
  async function submit(event) { event.preventDefault(); await perform(async () => { media.stopSpeaking(); const data = await aiRequest(`/interview/${session._id}/answer`, { questionIndex: index, answer }); setSession(data.session); setAnswer(''); if (data.session.status === 'completed') stopMedia(); await refresh(); }); }
  return <main className="min-h-screen bg-slate-50 py-10 px-4"><div className="max-w-6xl mx-auto space-y-6">
    <header><p className="text-blue-600 font-semibold">Practice • Feedback • Progress</p><h1 className="text-3xl font-bold mt-2">AI mock interview</h1><p className="text-slate-600 mt-2">AI writes questions and evaluates your reviewed answers. Each answer is saved automatically for your Career Coach.</p><Link className="text-blue-600 underline" to="/settings">Your profile</Link></header>
    {error && <p role="alert" className="rounded-xl bg-red-50 text-red-800 p-4">{error}</p>}
    <div className="grid lg:grid-cols-[1fr_300px] gap-6"><section className="bg-white rounded-2xl border p-5 sm:p-8">
      {!session ? <form onSubmit={start} className="space-y-5"><label className="block">Interview topic<input required maxLength={200} className={field} value={config.topic} onChange={e => setConfig({ ...config, topic: e.target.value })} placeholder="React developer, accounting, communication…" /></label><div className="grid sm:grid-cols-2 gap-4"><label>Level<select className={field} value={config.difficulty} onChange={e => setConfig({ ...config, difficulty: e.target.value })}>{['beginner', 'intermediate', 'advanced'].map(v => <option key={v}>{v}</option>)}</select></label><label>Questions<input type="number" min={3} max={10} required className={field} value={config.questionCount} onChange={e => setConfig({ ...config, questionCount: Number(e.target.value) })} /></label></div><LanguagePicker value={config.language} onChange={language => setConfig({ ...config, language })} /><label className="block">Interview mode<select className={field} value={config.mode} onChange={e => setConfig({ ...config, mode: e.target.value })}><option value="voice">Voice + transcript</option><option value="video">Voice + local camera preview</option><option value="text">Typed answers</option></select></label><p className="text-sm text-slate-600">Voice depends on browser speech support and installed voices. Any language can be entered with a valid language code; typed answers remain available. Camera preview stays on your device. AI evaluates transcript content.</p><button disabled={busy} className={button}>{busy ? 'Preparing your interview…' : 'Start AI interview'}</button></form> : <div className="space-y-5"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">{session.interviewConfig.topic}</h2><p className="text-sm text-slate-500">{session.interviewConfig.difficulty} • {session.interviewConfig.language} • {index}/{session.questions.length} answered</p></div><button disabled={busy} className="text-blue-600 underline" onClick={() => { stopMedia(); setSession(null); setAnswer(''); }}>New interview</button></div><progress className="w-full" max={session.questions.length} value={index} />
      {question ? <form onSubmit={submit} className="space-y-4"><h3 className="text-xl font-semibold whitespace-pre-wrap">{index + 1}. {question.question}</h3><div className="flex flex-wrap gap-2"><button type="button" disabled={busy || media.listening} className={button} onClick={() => media.speaking ? media.stopSpeaking() : media.speak(question.question)}>{media.speaking ? 'Stop question audio' : 'Read question aloud'}</button>{session.interviewConfig.mode !== 'text' && <button type="button" disabled={busy || media.micPending} className={button} onClick={() => media.listening ? media.stopListening() : media.startListening()}>{media.micPending ? 'Allow microphone…' : media.listening ? 'Stop microphone' : 'Speak your answer'}</button>}{session.interviewConfig.mode === 'video' && <button type="button" className={button} disabled={media.cameraPending || busy} onClick={() => media.camera ? media.stopCamera() : media.startCamera()}>{media.cameraPending ? 'Opening camera…' : media.camera ? 'Turn camera off' : 'Enable camera preview'}</button>}</div>
      {media.camera && <div><video ref={media.videoRef} autoPlay muted playsInline className="w-full max-w-md rounded-xl bg-black" /><p className="text-sm text-slate-500">Local preview only; no video recording or appearance scoring.</p></div>}{media.note && <p role="status" className="bg-amber-50 rounded-xl p-3 text-amber-900">{media.note}</p>}{media.interim && <p aria-live="polite" className="text-slate-500 italic">Listening: {media.interim}</p>}<label className="block font-medium">Review your answer<textarea required maxLength={10000} rows={8} className={`${field} mt-2 font-normal`} value={answer} disabled={busy} onChange={e => setAnswer(e.target.value)} placeholder="Speak, then stop the microphone and correct your transcript. You can also type here." /></label><p className="text-sm text-slate-500">{answer.length}/10,000 characters. Stop the microphone before submitting.</p><button disabled={busy || media.listening || media.micPending || !answer.trim()} className={button}>{busy ? 'AI is evaluating and saving…' : 'Submit reviewed answer'}</button></form> : <div className="rounded-xl bg-blue-50 p-5"><h3 className="text-xl font-bold">Interview completed</h3><p className="mt-2">AI assessment: {session.averageScore}/10</p><p className="text-sm mt-2">Practice feedback is based on your answers; it is not an employer assessment.</p></div>}
      {session.answers.length > 0 && <div className="space-y-3"><h3 className="font-semibold">Saved feedback</h3>{session.answers.map((item, i) => <details key={i} className="border rounded-xl p-4" open={i === session.answers.length - 1}><summary className="cursor-pointer font-medium">Question {i + 1} · {item.evaluation.score}/10</summary><p className="mt-3 font-medium">{item.question}</p><p className="whitespace-pre-wrap text-slate-600 my-3">{item.answer}</p><p className="whitespace-pre-wrap">{item.evaluation.feedback}</p>{['strengths', 'improvements'].map(key => <div key={key} className="mt-3"><h4 className="font-semibold capitalize">{key}</h4><ul className="list-disc pl-5">{item.evaluation[key]?.map((value, j) => <li key={j}>{value}</li>)}</ul></div>)}</details>)}</div>}</div>}
    </section><aside className="bg-white border rounded-2xl p-5 self-start"><h2 className="text-lg font-semibold">Saved interviews</h2><p className="text-sm text-slate-500 mt-1">Resume an unfinished session or review feedback.</p><div className="space-y-3 mt-4">{history.length === 0 && <p className="text-sm">No saved sessions yet.</p>}{history.map(item => <div key={item._id} className="border rounded-xl p-3"><button disabled={busy} className="text-left text-blue-700 font-medium" onClick={() => open(item._id)}>{item.interviewConfig?.topic || 'Interview'}</button><p className="text-sm text-slate-500">{item.status} · {item.averageScore == null ? 'Not evaluated' : `${item.averageScore}/10`}</p><button disabled={busy} className="text-sm text-red-700 mt-2" onClick={() => { if (window.confirm('Delete this saved interview?')) perform(async () => { await resumeRequest(`/api/interviews/${item._id}`, { method: 'DELETE' }); if (session?._id === item._id) { stopMedia(); setSession(null); } await refresh(); }); }}>Delete</button></div>)}</div></aside></div>
  </div></main>;
}
